---
version: 2
updates:
  - package-ecosystem: "gitsubmodule"  # See documentation for possible values
    directory: "/"  # Location of package manifests
    schedule:
      interval: "weekly"

    allow:
      - dependency-name: "external/pipeline-Nextflow-config"
      - dependency-name: "external/pipeline-Nextflow-module"
