---
input_csv:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to input CSV if inputs are being provided through CSV'
output_dir:
  type: 'Path'
  mode: 'w'
  required: true
  help: 'Absolute path to output directory'
leading_work_dir:
  type: 'Path'
  mode: 'w'
  required: true
  help: 'Absolute path to leading job working directory; should be a common directory under /hot'
project_id:
  type: 'String'
  required: true
  help: 'Project ID'
save_intermediate_files:
  type: 'Bool'
  required: true
  default: false
  help: 'Whether to save metapipeline intermediate files'
partition:
  type: 'String'
  required: true
  choices: ['F16', 'F32', 'F72', 'F72_3TB']
  help: 'Partition type to submit jobs to'
clusterOptions:
  type: 'String'
  required: true
  allow_empty: true
  help: 'Additional cluster options for use with submission command'
status_email_address:
  type: 'EmailAddress'
  required: false
  allow_empty: true
  help: 'If given, the address to which pipeline start/complete notifications will be sent'
max_parallel_jobs:
  type: 'Integer'
  required: true
  default: 5
  help: 'Maximum number of jobs to launch in parallel'
cluster_submission_interval:
  type: 'Integer'
  required: true
  default: 30
  help: 'Time between each job submission in minutes'
sample_mode:
  type: 'String'
  required: true
  choices: ['single', 'multi', 'paired']
  help: 'Mode in which to process the input samples'
run_downstream_pipelines_serially:
  type: 'Bool'
  required: true
  default: false
  help: 'Let pipelines downstream of recalibrate-BAM run sequentially regardless of whether an ordering has been specified or not'
override_src_precursor_disable:
  type: 'Bool'
  required: true
  default: false
  help: 'Override the defauly behavior of skipping pipelines that are used to generate inputs for call-SRC when those inputs are already provided'
src_snv_tool:
  type: 'String'
  required: true
  choices:
    - BCFtools-Intersect
    - Mutect2
    - SomaticSniper
    - Strelka2
    - MuSE
  default: 'BCFtools-Intersect'
  help: 'The tool used for SNV calling to generate the input for call-SRC'
src_cna_tool:
  type: 'String'
  required: true
  choices:
    - FACETS
    - Battenberg
  default: 'Battenberg'
  help: 'The tool used for CNA calling to generate the input for call-SRC'
src_run_all_combinations:
  type: 'Bool'
  required: false
  default: false
  help: 'Whether to run all possible combinations of SNV and CNA tools for call-SRC'
downstream_pipeline_order:
  type: 'List'
  required: false
  choices:
    - generate-SQC-BAM
    - call-gSNP
    - call-gSV
    - call-mtSNV
    - call-sSNV
    - call-sSV
    - call-sCNA
  help: 'Ordered list for defining custom pipeline run order'
requested_pipelines:
  type: 'List'
  required: true
  default:
    - align-DNA
    - recalibrate-BAM
    - generate-SQC-BAM
    - call-gSNP
    - call-gSV
    - call-mtSNV
    - call-sSNV
    - call-sSV
    - call-sCNA
    - call-SRC
  choices:
    - align-DNA
    - recalibrate-BAM
    - calculate-targeted-coverage
    - generate-SQC-BAM
    - call-gSNP
    - call-gSV
    - call-mtSNV
    - call-sSNV
    - call-sSV
    - call-sCNA
    - call-SRC
    - StableLiftsSNV
    - StableLiftgSV
    - StableLiftsSV
  help: 'List of pipelines to run'
override_realignment:
  type: 'Bool'
  required: true
  default: false
  help: 'Whether to override and skip back-conversion to FASTQ and realignment with align-DNA'
override_recalibrate_bam:
  type: 'Bool'
  required: true
  default: false
  help: 'Whether to override and skip recalibrate-BAM'
use_original_intervals:
  type: 'Bool'
  required: false
  default: false
  help: 'Whether to use the original given intervals rather than the expanded intervals generated through targeted-coverage'
uclahs_cds_wgs:
  type: 'Bool'
  required: true
  default: true
  help: 'Whether to enable global job limiter when processing large WGS samples'
global_allowed_jobs:
  type: 'Integer'
  required: true
  default: 12
  help: 'Maximum number of jobs to run in parallel cluster-wide'
per_user_allowed_jobs:
  type: 'Integer'
  required: true
  default: 3
  help: 'Max number of large WGS jobs allowed per user'
global_rate_limit:
  type: 'Integer'
  required: true
  default: 90
  help: 'Time intervals between submissions of large WGS jobs'
global_job_submission_limiter:
  type: 'String'
  required: true
  allow_empty: true
  help: 'Limiter wrapper for metapipeline job submission'
global_job_submission_sbatch:
  type: 'String'
  required: true
  allow_empty: true
  help: 'Sbatch command for submitting metapipeline job'
stablelift_models:
  type: 'StableLiftModels'
  required: true
  help: 'Map of paths to StableLift models'
pipeline_params:
  type: 'Namespace'
  required: true
  help: 'Pipeline-specific parameters'
  elements:
    convert_BAM2FASTQ:
      type: 'Namespace'
      required: true
      help: 'Parameters for convert-BAM2FASTQ'
    align_DNA:
      type: 'Namespace'
      required: true
      help: 'Parameters for align-DNA'
    recalibrate_BAM:
      type: 'Namespace'
      required: true
      help: 'Parameters for recalibrate-BAM'
    call_gSNP:
      type: 'Namespace'
      required: true
      help: 'Parameters for call-gSNP'
    call_sSNV:
      type: 'Namespace'
      required: true
      help: 'Parameters for call-sSNV'
    call_mtSNV:
      type: 'Namespace'
      required: true
      help: 'Parameters for call-mtSNV'
    call_gSV:
      type: 'Namespace'
      required: true
      help: 'Parameters for call-gSV'
    call_sSV:
      type: 'Namespace'
      required: true
      help: 'Parameters for call-sSV'
    call_sCNA:
      type: 'Namespace'
      required: true
      help: 'Parameters for call-sCNA'
    calculate_targeted_coverage:
      type: 'Namespace'
      required: true
      help: 'Parameters for calculate-targeted-coverage'
    generate_SQC_BAM:
      type: 'Namespace'
      required: true
      help: 'Parameters for generate-SQC-BAM'
    StableLift:
      type: 'Namespace'
      required: true
      help: 'Parameters for StableLift'
input:
  type: 'InputNamespace'
  required: true
  help: 'Input to process'
  elements:
    Patient:
      type: 'PatientNamespace'
      required: true
      help: 'Namespace containing information about patient'
      elements:
        Sample:
          type: 'SampleNamespace'
          required: true
          help: 'Namespace containing information about sample'
          elements:
            state:
              type: 'String'
              required: true
              choices: ['normal', 'tumor']
              help: 'State of tissue from which sample was obtained'
            CRAM:
              type: 'Namespace'
              required: false
              help: 'Inputs CRAM'
              elements:
                path:
                  type: 'Path'
                  mode: 'r'
                  required: true
                  help: 'Path to the CRAM file'
            BAM:
              type: 'Namespace'
              required: false
              help: 'Inputs BAM'
              elements:
                path:
                  type: 'Path'
                  mode: 'r'
                  required: true
                  help: 'Path to the BAM file'
            FASTQ:
              type: 'EntryList'
              required: false
              help: 'Inputs FASTQs'
              elements:
                read_group_identifier:
                  type: 'String'
                  required: true
                  help: 'Read group identifier for alignment'
                sequencing_center:
                  type: 'String'
                  required: true
                  help: 'Center where sequencing was performed'
                library_identifier:
                  type: 'String'
                  required: true
                  help: 'Library used for sample'
                platform_technology:
                  type: 'String'
                  required: true
                  help: 'Technology used for sequencing'
                platform_unit:
                  type: 'String'
                  required: true
                  help: 'Name of specific platform unit'
                bam_header_sm:
                  type: 'String'
                  required: true
                  help: 'Sample name tag for BAM'
                lane:
                  type: 'LaneType'
                  required: true
                  help: 'Lane'
                read1_fastq:
                  type: 'Path'
                  mode: 'r'
                  required: true
                  help: 'Absolute path to R1 FASTQ'
                read2_fastq:
                  type: 'Path'
                  mode: 'r'
                  required: true
                  help: 'Absolute path to R2 FASTQ'
            SRC:
              type: 'EntryList'
              required: false
              help: 'Inputs SRC'
              elements:
                src_input_type:
                  type: 'String'
                  required: true
                  choices: ['SNV', 'CNA']
                  help: 'Type of input'
                algorithm:
                  type: 'String'
                  required: true
                  choices:
                    - BCFtools-Intersect
                    - Mutect2
                    - SomaticSniper
                    - Strelka2
                    - MuSE
                    - FACETS
                    - Battenberg
                  help: 'Tool used to call input'
                path:
                  type: 'Path'
                  mode: 'r'
                  required: true
                  help: 'Absolute path to calls'
